name: auto-labeler

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Labeler
        uses: release-drafter/release-drafter@v5
        with:
          # only run auto-labeler for PRs
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
