name: build
on:
  push:
    branches:
      - '**'

jobs:
  validation:
    name: "gradle-wrapper-validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
  build:
    name: "gradle-build"
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Setup and Execute Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -s --scan
        env:
          # NOTE: using global token because we're pulling dependencies from different repositories
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_REGISTRY }}
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          registry-url: 'https://npm.pkg.github.com/'
      - name: Build NPM
        run: |
          npm ci
          npm run build
