name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: build
        run: |
          ./gradlew build
      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4.4.3
        with:
          name: kp-protocols-clientsdk.pb
          path: "**/build/*/image.binpb"
