name: build
on:
  push:
    branches:
      - '**'
jobs:
  gradle:
    uses: kodypay/kp-github-workflows/.github/workflows/gradle-lib-build.yaml@main
    secrets: inherit
    with:
      java_version: 17
