name: release

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: [ build ]
    types: [ completed ]
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE }}
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Tag Name
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag=${TAG_NAME}" >> $GITHUB_ENV

      - name: Dispatch PHP SDK
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: kodypay/kody-clientsdk-php
          client-payload: '{"tag": "${{ env.tag }}", "repository": "${{ github.repository }}"}'
          event-type: tag-push
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
