name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch PHP SDK
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: kodypay/kody-clientsdk-php7-forked
          client-payload: '{"tag": "${{ github.ref }}", "repository": "${{ github.repository }}"}'
          event-type: tag-push
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
