name: release

on:
  workflow_dispatch:
    inputs:
      sdk_language:
        description: 'SDK Language'
        required: true
        type: choice
        options:
          - php
          - kotlin
          - all

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Tag Name
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag=${TAG_NAME}" >> $GITHUB_ENV

      - name: Dispatch PHP SDK
        if: ${{ github.event.inputs.sdk_language == 'php' || github.event.inputs.sdk_language == 'all' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: kodypay/kody-clientsdk-php
          client-payload: '{"tag": "${{ env.tag }}", "repository": "${{ github.repository }}"}'
          event-type: tag-push
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Dispatch Kotlin SDK
        if: ${{ github.event.inputs.sdk_language == 'kotlin' || github.event.inputs.sdk_language == 'all' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: kodypay/kody-clientsdk-kotlin
          client-payload: '{"tag": "${{ env.tag }}", "repository": "${{ github.repository }}"}'
          event-type: tag-push
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
